version: '3.8'

services:
  python-app:
    image: python:3.10
    container_name: SIC_Capstone_School
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - ../:/app

    command: >
      bash -c "pip install --no-cache-dir -r requirements.txt &&
      jupyter nbconvert --to script SIC_Capstone_School.ipynb --output test/CitySimulation &&
      cd test &&
      python -m unittest test_city_simulation.py"